---
#########################################################
# Setup Configuration for Pipeline Simulation
#########################################################
version: 1.0.0
 
# Git repositories to clone
repositories:
  - name: dbb
    url: https://github.com/IBM/dbb.git
    target_dir: dbb

# zBuilder framework configuration
zbuilder:
  # Local source directory (relative to .setup)
  source_dir: build
  
  # Target USS directory for upload
  target_dir: $PIPELINE_WORKSPACE/zBuilder
  
  # Languages configuration file
  languages_config: build/languages/Languages.yaml

# Pipeline simulation script
pipeline_script:
  # Target USS location
  target: $PIPELINE_WORKSPACE/pipeline_simulation.sh

  # Local source file
  source: pipeline_simulation.sh
  
  # workspace directory
  workspace: $PIPELINE_WORKSPACE/workspace

# Made with Bob
